# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wenyan Li
email: wenyanli@umd.edu
description: > # this means to ignore newlines until "baseurl:"
  Webpage of Wenyan Li
baseurl: "/startjekyll" # the subpath of your site, e.g. /blog
url: "http://lyan62.github.io" # the base hostname & protocol for your site

# Social
facebook: Wenyan Li
github_username:  lyan62

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
